version: '3.7'

services:
  espnet-tts-serving:
    image: airenas/espnet-tts-serving:${SERVICE_VERSION}
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      CONFIG_FILE: /config/voices.yaml
      DEVICE: cpu
      WORKERS: 1
    # restart: unless-stopped
    volumes:
      - ${MODELS_PATH}:/models:ro
      - ./voices.yaml:/config/voices.yaml:ro
