version: '3.7'

services:
  espnet-tts-serving:
    image: airenas/espnet-tts-serving-gpu:${SERVICE_VERSION}
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all
      CONFIG_FILE: /config/voices.yaml
      WORKERS: 1
        # restart: unless-stopped
    volumes:
      - ${MODELS_PATH}:/models:ro
      - ./voices.yaml:/config/voices.yaml:ro
    runtime: nvidia
