version: '3.7'

services:
  espnet-tts-serving:
    image: airenas/espnet-tts-serving:${SERVICE_VERSION}
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      MODEL_ZIP_PATH: "/model/${MODEL}"
      DEVICE: ${DEVICE}
    # restart: unless-stopped
    volumes:
      - ${MODEL_PATH}:/model
