# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install sndfile
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_cpu.txt ]; then pip install -r requirements_cpu.txt; fi
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
      - name: Lint with flake8
        run: |
          make test/lint
      - name: Test with pytest
        run: |
          make test/unit
      - name: Generate coverage report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pytest --cov=.
          coveralls
